# frozen_string_literal: true

# Build-time image upgrades, driven by _data/images.json (generated by tools/images.py):
#   * width/height on every known <img> (no layout shift)
#   * loading="lazy" + decoding="async" unless the tag already says otherwise
#   * a <picture> with WebP sources (480w / 960w / full) and a `sizes` hint, so phones get small files
# Images not in the manifest, external images and images inside <picture> or <noscript> are left untouched.
# Pages only ever reference the original file, so content stays portable.
module CornerstoneImages
  IMG = /<img\b[^>]*>/i.freeze
  DEFAULT_SIZES = "(min-width: 1200px) 848px, (min-width: 992px) 698px, (min-width: 768px) 720px, 100vw"

  module_function

  def attr(tag, name)
    m = tag.match(/\s#{name}\s*=\s*(["'])(.*?)\1/i)
    m && m[2]
  end

  def set_attr(tag, name, value)
    return tag if tag =~ /\s#{name}\s*=/i
    tag.sub(/\s*\/?>\z/) { |close| %( #{name}="#{value}"#{close}) }
  end

  def upgrade(html, site)
    manifest = site.data["images"]
    return html unless manifest.is_a?(Hash) && !manifest.empty?

    base = site.config["baseurl"].to_s
    host = site.config["url"].to_s
    out = +""
    pos = 0
    html.scan(IMG) do
      m = Regexp.last_match
      tag = m[0]
      start = m.begin(0)
      out << html[pos...start]
      pos = m.end(0)
      before = html[[0, start - 200].max...start]
      if before =~ /<picture\b(?![\s\S]*<\/picture>)/i || before =~ /<noscript\b(?![\s\S]*<\/noscript>)/i
        out << tag
        next
      end
      src = attr(tag, "src").to_s
      key = src.sub(/\A#{Regexp.escape(host)}/, "").sub(/\A#{Regexp.escape(base)}(?=\/)/, "").sub(/[?#].*\z/, "")
      info = manifest[key]
      unless info
        out << tag
        next
      end
      t = tag.dup
      unless attr(t, "width") || attr(t, "height")
        t = set_attr(t, "width", info["w"])
        t = set_attr(t, "height", info["h"])
      end
      eager = attr(t, "loading") || attr(t, "fetchpriority")
      t = set_attr(t, "loading", "lazy") unless eager
      t = set_attr(t, "decoding", "async")
      variants = Array(info["webp"])
      if variants.empty?
        out << t
        next
      end
      srcset = variants.map { |w, u| "#{base}#{u} #{w}w" }.join(", ")
      sizes = attr(t, "sizes") || attr(t, "data-sizes") || DEFAULT_SIZES
      t = t.sub(/\s+data-sizes\s*=\s*(["']).*?\1/i, "")
      out << %(<picture><source type="image/webp" srcset="#{srcset}" sizes="#{sizes}">#{t}</picture>)
    end
    out << html[pos..] if pos < html.length
    out
  end
end

Jekyll::Hooks.register [:pages, :documents], :post_render do |doc|
  next unless doc.output_ext == ".html" && doc.output
  doc.output = CornerstoneImages.upgrade(doc.output, doc.site)
end
